# golangci-lint configuration for WOSM project
# yaml-language-server: disable

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

  disable:
    - gochecknoglobals

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
